{{- if (or (and (ne (.Values.client.enabled | toString) "-") .Values.client.enabled) (and (eq (.Values.client.enabled | toString) "-") .Values.global.enabled)) }}
# ConfigMap with extra configuration specified directly to the chart
# for client agents only.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "consul.fullname" . }}-client-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: client
data:
  client.json: |-
    {
      {{- if and .Values.global.secretsBackend.vault.enabled }}
      "auto_reload_config": true
      {{- end }}
    }
  extra-from-values.json: |-
{{ tpl .Values.client.extraConfig . | trimAll "\"" | indent 4 }}
  central-config.json: |-
    {
      "enable_central_service_config": true
    }

  {{- if .Values.connectInject.enabled }}
  {{/* We set check_update_interval to 0s so that check output is immediately viewable
       in the UI. */}}
  config.json: |-
    {
      "check_update_interval": "0s"
    }
  {{- end }}
{{- end }}
