{{- if .Values.connectInject.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "consul.fullname" . }}-gateway-resources-ocp
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: gateway-resources-ocp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "consul.fullname" . }}-gateway-resources-ocp
subjects:
  - kind: ServiceAccount
    name: {{ template "consul.fullname" . }}-gateway-resources-ocp
    namespace: {{ .Release.Namespace }}
{{- end }}