{{- if .Values.connectInject.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "consul.fullname" . }}-pvc-cleaner-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: generate-manifests-pvc-cleaner
  annotations:
    "helm.sh/hook": post-upgrade, post-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ template "consul.fullname" . }}-pvc-cleaner-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "consul.fullname" . }}-pvc-cleaner-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}