{{- if .Values.connectInject.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "consul.fullname" . }}-generate-manifests
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: generate-manifests
  metadata:
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "consul.fullname" . }}-generate-manifests
subjects:
  - kind: ServiceAccount
    name: {{ template "consul.fullname" . }}-generate-manifests
    namespace: {{ .Release.Namespace }}
{{- end }}