{{- $serverEnabled := (or (and (ne (.Values.server.enabled | toString) "-") .Values.server.enabled) (and (eq (.Values.server.enabled | toString) "-") .Values.global.enabled)) -}}
{{- if (and .Values.global.adminPartitions.enabled $serverEnabled) }}
# Service with an external IP for clients in non-default Admin Partitions
# to discover Consul servers. This service should only point to Consul servers.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "consul.fullname" . }}-partition-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: server
  annotations:
    {{- if .Values.global.adminPartitions.service.annotations }}
    {{ tpl .Values.global.adminPartitions.service.annotations . | nindent 4 | trim }}
    {{- end }}
spec:
  type: "{{ .Values.global.adminPartitions.service.type }}"
  ports:
    - name: https
      port: 8501
      targetPort: 8501
      {{ if (and (eq .Values.global.adminPartitions.service.type "NodePort") .Values.global.adminPartitions.service.nodePort.https) }}
      nodePort: {{ .Values.global.adminPartitions.service.nodePort.https }}
      {{- end }}
    - name: serflan
      port: 8301
      targetPort: 8301
      {{ if (and (eq .Values.global.adminPartitions.service.type "NodePort") .Values.global.adminPartitions.service.nodePort.serf) }}
      nodePort: {{ .Values.global.adminPartitions.service.nodePort.serf }}
      {{- end }}
    - name: server
      port: 8300
      targetPort: 8300
      {{ if (and (eq .Values.global.adminPartitions.service.type "NodePort") .Values.global.adminPartitions.service.nodePort.rpc) }}
      nodePort: {{ .Values.global.adminPartitions.service.nodePort.rpc }}
      {{- end }}
  selector:
    app: {{ template "consul.name" . }}
    release: "{{ .Release.Name }}"
    component: server
{{- end }}
