{{- if .Values.terminatingGateways.enabled }}
{{- if .Values.global.rbac.create }}
{{- $root := . }}
{{- $defaults := .Values.terminatingGateways.defaults }}

{{- range .Values.terminatingGateways.gateways }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ template "consul.fullname" $root }}-{{ .name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app: {{ template "consul.name" $root }}
    chart: {{ template "consul.chart" $root }}
    heritage: {{ $root.Release.Service }}
    release: {{ $root.Release.Name }}
    component: terminating-gateway
    terminating-gateway-name: {{ template "consul.fullname" $root }}-{{ .name }}
{{- if $root.Values.global.enablePodSecurityPolicies }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
      -  {{ template "consul.fullname" $root }}-{{ .name }}
    verbs:
      - use
{{- else }}
rules: []
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}