{{- if (and (or .Values.connectInject.enabled .Values.controller.enabled) (not .Values.global.secretsBackend.vault.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "consul.fullname" . }}-webhook-cert-manager-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: webhook-cert-manager
data:
  webhook-config.json: |-
    [
    {{- if .Values.connectInject.enabled }}
      {
        "name": "{{ template "consul.fullname" . }}-connect-injector",
        "tlsAutoHosts": [
          "{{ template "consul.fullname" . }}-connect-injector",
          "{{ template "consul.fullname" . }}-connect-injector.{{ .Release.Namespace }}",
          "{{ template "consul.fullname" . }}-connect-injector.{{ .Release.Namespace }}.svc",
          "{{ template "consul.fullname" . }}-connect-injector.{{ .Release.Namespace }}.svc.cluster.local"
        ],
        "secretName": "{{ template "consul.fullname" . }}-connect-inject-webhook-cert",
        "secretNamespace": "{{ .Release.Namespace }}"
      }{{- if and .Values.controller.enabled }},{{- end }}{{- end }}
    {{- if and .Values.controller.enabled }}
      {
        "name": "{{ template "consul.fullname" . }}-controller",
        "tlsAutoHosts": [
          "{{ template "consul.fullname" . }}-controller-webhook",
          "{{ template "consul.fullname" . }}-controller-webhook.{{ .Release.Namespace }}",
          "{{ template "consul.fullname" . }}-controller-webhook.{{ .Release.Namespace }}.svc",
          "{{ template "consul.fullname" . }}-controller-webhook.{{ .Release.Namespace }}.svc.cluster.local"
        ],
        "secretName": "{{ template "consul.fullname" . }}-controller-webhook-cert",
        "secretNamespace": "{{ .Release.Namespace }}"
      }
    {{- end }}
    ]
  {{- end }}
