{{- if (and (or .Values.connectInject.enabled .Values.controller.enabled) (not .Values.global.secretsBackend.vault.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "consul.fullname" . }}-webhook-cert-manager
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: webhook-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "consul.fullname" . }}-webhook-cert-manager
subjects:
- kind: ServiceAccount
  name: {{ template "consul.fullname" . }}-webhook-cert-manager
  namespace: {{ .Release.Namespace }}
{{- end }}
