{{- if .Values.controller.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "consul.fullname" . }}-controller-mutating-webhook-configuration
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: controller
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-proxydefaults
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-proxydefaults.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - proxydefaults
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-mesh
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-mesh.consul.hashicorp.com
  rules:
    - apiGroups:
      - consul.hashicorp.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - meshes
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicedefaults
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-servicedefaults.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicedefaults
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-serviceresolver
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-serviceresolver.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceresolvers
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicerouter
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-servicerouter.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicerouters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-servicesplitter
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-servicesplitter.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicesplitters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-serviceintentions
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-serviceintentions.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceintentions
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-ingressgateway
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-ingressgateway.consul.hashicorp.com
  rules:
  - apiGroups:
      - consul.hashicorp.com
    apiVersions:
      - v1alpha1
    operations:
      - CREATE
      - UPDATE
    resources:
      - ingressgateways
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "consul.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1alpha1-terminatinggateway
  failurePolicy: Fail
  admissionReviewVersions:
  - "v1beta1"
  - "v1"
  name: mutate-terminatinggateway.consul.hashicorp.com
  rules:
  - apiGroups:
      - consul.hashicorp.com
    apiVersions:
      - v1alpha1
    operations:
      - CREATE
      - UPDATE
    resources:
      - terminatinggateways
  sideEffects: None
{{- end }}
