# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v2beta1-grpcroute
  failurePolicy: Fail
  name: mutate-grpcroute.auth.consul.hashicorp.com
  rules:
  - apiGroups:
    - auth.consul.hashicorp.com
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - grpcroute
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v2beta1-httproute
  failurePolicy: Fail
  name: mutate-httproute.auth.consul.hashicorp.com
  rules:
  - apiGroups:
    - auth.consul.hashicorp.com
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httproute
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v2beta1-proxyconfiguration
  failurePolicy: Fail
  name: mutate-proxyconfiguration.auth.consul.hashicorp.com
  rules:
  - apiGroups:
    - auth.consul.hashicorp.com
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxyconfiguration
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v2beta1-tcproute
  failurePolicy: Fail
  name: mutate-tcproute.auth.consul.hashicorp.com
  rules:
  - apiGroups:
    - auth.consul.hashicorp.com
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tcproute
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-controlplanerequestlimits
  failurePolicy: Fail
  name: mutate-controlplanerequestlimits.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - controlplanerequestlimits
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-exportedservices
  failurePolicy: Fail
  name: mutate-exportedservices.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exportedservices
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-ingressgateway
  failurePolicy: Fail
  name: mutate-ingressgateway.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressgateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-jwtprovider
  failurePolicy: Fail
  name: mutate-jwtprovider.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jwtproviders
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-mesh
  failurePolicy: Fail
  name: mutate-mesh.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mesh
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-peeringacceptors
  failurePolicy: Fail
  name: mutate-peeringacceptors.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peeringacceptors
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-peeringdialers
  failurePolicy: Fail
  name: mutate-peeringdialers.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peeringdialers
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-proxydefaults
  failurePolicy: Fail
  name: mutate-proxydefaults.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxydefaults
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-samenessgroups
  failurePolicy: Fail
  name: mutate-samenessgroup.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - samenessgroups
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-servicedefaults
  failurePolicy: Fail
  name: mutate-servicedefaults.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicedefaults
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-serviceintentions
  failurePolicy: Fail
  name: mutate-serviceintentions.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceintentions
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-serviceresolver
  failurePolicy: Fail
  name: mutate-serviceresolver.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceresolvers
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-servicerouter
  failurePolicy: Fail
  name: mutate-servicerouter.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicerouters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-servicesplitter
  failurePolicy: Fail
  name: mutate-servicesplitter.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicesplitters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1alpha1-terminatinggateway
  failurePolicy: Fail
  name: mutate-terminatinggateway.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - terminatinggateways
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v2beta1-trafficpermissions
  failurePolicy: Fail
  name: mutate-trafficpermissions.auth.consul.hashicorp.com
  rules:
  - apiGroups:
    - auth.consul.hashicorp.com
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - trafficpermissions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1alpha1-gatewaypolicy
  failurePolicy: Fail
  name: validate-gatewaypolicy.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gatewaypolicies
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1alpha1-registration
  failurePolicy: Fail
  name: validate-registration.consul.hashicorp.com
  rules:
  - apiGroups:
    - consul.hashicorp.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registrations
  sideEffects: None
