resources:
- consul.networking.io_gatewayclasses.yaml
- consul.networking.io_gateways.yaml
- consul.networking.io_httproutes.yaml
- consul.networking.io_referencegrants.yaml
- consul.networking.io_tcproutes.yaml
- consul.networking.io_tlsroutes.yaml
- consul.networking.io_udproutes.yaml
- consul.networking.io_grpcroutes.yaml
