# Copyright (c) HashiCorp, Inc.

---
name: Backport Assistant Runner

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:v0.5.8
    steps:
      - name: Run Backport Assistant
        run: backport-assistant backport -merge-method=squash -gh-automerge
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.x)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          BACKPORT_MERGE_COMMIT: true
          ENABLE_VERSION_MANIFESTS: true
