# Dispatch to the consul-k8s-workflows with a nightly cron
name: nightly-acceptance
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run nightly at 12AM UTC/8PM EST/5PM PST
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        default: 'main'
        type: string
      context:
        description: 'Context for the test run'
        required: false
        default: 'manual-dispatch'
        type: string

# these should be the only settings that you will ever need to change
env:
  BRANCH: ${{ github.event.inputs.branch || github.ref_name }}
  CONTEXT: ${{ github.event.inputs.context || 'nightly' }}

jobs:
  cloud:
    name: cloud
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@25b02cc069be46d637e8fe2f1e8484008e9e9609 # v1.2.3
      name: cloud
      with:
        workflow: cloud.yml
        repo: hashicorp/consul-k8s-workflows
        ref: main
        token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        inputs: '{ "context":"${{ env.CONTEXT }}", "repository":"${{ github.repository }}", "branch":"${{ env.BRANCH }}", "sha":"${{ github.sha }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
