# Dispatch to the consul-k8s-workflows with a nightly cron
name: nightly-acceptance
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run nightly at 12AM UTC/8PM EST/5PM PST
    - cron:  '0 0 * * *'

# these should be the only settings that you will ever need to change
env:
  BRANCH: ${{ github.ref_name }}
  CONTEXT: "nightly"

jobs:
  cloud:
    name: cloud
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@v1.2.2
      name: cloud
      with:
        workflow: cloud.yml
        repo: hashicorp/consul-k8s-workflows
        ref: main
        token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        inputs: '{ "test-ce": false, "context":"${{ env.CONTEXT }}", "repository":"${{ github.repository }}", "branch":"${{ env.BRANCH }}", "sha":"${{ github.sha }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
