# Dispatch to the consul-k8s-workflows with a nightly cron
name: pr-oc-acceptance
on:
  push:
    branches:
      - "anilvpatel/test-oc-acceptance"

# these should be the only settings that you will ever need to change
env:
  BRANCH: "anilvpatel/test-oc-acceptance"
  CONTEXT: "push"

jobs:
  cloud-acceptance:
    name: cloud-acceptance
    runs-on: ubuntu-24.04
    steps:
      - uses: benc-uk/workflow-dispatch@25b02cc069be46d637e8fe2f1e8484008e9e9609 # v1.2.3
        name: cloud
        with:
          workflow: cloud.yml
          repo: hashicorp/consul-k8s-workflows
          ref: "anilvpatel/openshift-acceptance-test"
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          inputs: '{ "context":"${{ env.CONTEXT }}-${{ github.run_id }}", "repository":"${{ github.repository }}", "branch":"${{ env.BRANCH }}", "sha":"${{ github.sha }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
