# Dispatch to the consul-k8s-workflows with a weekly cron
#
# A separate file is needed for each release because the cron schedules are different for each release.
name: weekly-acceptance-1-7-x
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run weekly on Sunday at 3AM UTC/11PM EST/8PM PST
    - cron:  '0 3 * * 7'

# these should be the only settings that you will ever need to change
env:
  BRANCH: "release/1.7.x"
  CONTEXT: "weekly"

jobs:
  cloud:
    name: cloud
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@25b02cc069be46d637e8fe2f1e8484008e9e9609 # v1.2.3
        name: cloud
        with:
          workflow: cloud.yml
          repo: hashicorp/consul-k8s-workflows
          ref: main
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          inputs: '{ "context":"${{ env.CONTEXT }}", "repository":"${{ github.repository }}", "branch":"${{ env.BRANCH }}", "sha":"${{ github.sha }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'